services:
  nightscout:
    image: nightscout/cgm-remote-monitor:latest
    env_file:
      - .env
    ports:
      - "8080:80"
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:latest
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
